spring.application.name=order-management

spring.mongodb.uri=mongodb://admin:Manzikert.1071@localhost:27017/multiterra?authSource=admin
spring.mongodb.representation.uuid=standard

server.port=8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tunahan.aydin2707@gmail.com
spring.mail.password=hzcy idta szsr azep

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true