spring.application.name=order-management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8083}
spring.jpa.hibernate.ddl-auto=update

resend.api.key=${RESEND_API_KEY}

customer.service.url=${CUSTOMER_SERVICE_URL}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest